fanclub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls')),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

page/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('leave_comment', views.leave_comment, name = 'leave_comment'),
    path('comment/', views.AddComment.as_view(), name='add_comment')
]

page/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    author_name = models.CharField('имя автора', max_length = 50)
    comment_text = models.CharField('текст комментария', max_length = 200)
    photo = models.ImageField(upload_to='user_photo/')
    
    def __str__(self):
        return self.author_name

page/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.http import HttpResponse, HttpResponseRedirect
from .models import Comment
from .form import CommentForm
from django.urls import reverse_lazy

class AddComment(CreateView):
    latest_comment_list = Comment.objects.order_by('-id')[:10]# новый
    model = Comment
    form_class = CommentForm
    template_name = 'index.html'
    success_url = reverse_lazy('index')

# Create your views here.
def index(request):
    counter = len(Comment.objects.all())
    latest_comment_list = Comment.objects.order_by('-id')[:10]
    return render(request, 'index.html', {'latest_comment_list': latest_comment_list, 'counter': counter})
    
def leave_comment(request):
    c = Comment(comment_text = request.POST['comment_text'], author_name = request.POST['author_name'], photo = request.FILES['photo'])
    c.save()
    return HttpResponseRedirect(reverse_lazy('index'))
    

page/templates/index.html
<!DOCTYPE>
{% load static %}
<html lang='ru'>
	<head>
		<meta charset=''UTF-8>
		<title>Фанклуб</title>
		<link rel="stylesheet" href="{% static 'css/style2.css' %}">
	</head>
	<body>
	<div class='container'>
		<header>
			<h1>Фан-клуб</h1>
			<p class="name">Кати Сычёвой</p>
		</header>
		
		<div class="text">
		<section>
			<h2>Почему Катя?</h2>
			<ul>
			<li>Самая милая девушка</li>
			<li>Классно танцует</li>
			<li>Потрясающий дизайнер</li>
			<li>Вкусно готовит</li>
			<li>Интересный собеседник</li>
			</ul>
		</section>
		
		<h2>И ТЫ ДО СИХ ПОР НЕ С НАМИ?!</h2>
		<hr>
		<p align='center'>Присоединяйтесь к нам</p>
		<p align='center'>Нас уже {{ counter }}!</p>
		<form action='{% url "leave_comment" %}' method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<p><label for="id_author_name"></label> <input type="text" class='textbox' name="author_name" maxlength="50" placeholder="Ваше имя" required id="id_author_name"></p>
			<p><label for="id_comment_text"></label> <textarea type="text" class='message' name="comment_text" placeholder="Текст комментария" maxlength="200" required id="id_comment_text"></textarea></p>
			<p ><label for="id_photo" class='file'>Фото</label> <input type="file" name="photo" accept="image/*" required id="id_photo"></p>
			<button type="submit" class='button'>Отправить</button>
		</form>
		<br>
		<hr>
		{% for c in latest_comment_list %}
			<p>
				
				<div class='photo'><img src='{{c.photo.url}}' height='100' width='100'></div>
				<div class='author'><strong>{{c.author_name}}</strong></div>
				<br>
				<div class='comment'><p>{{c.comment_text}}</p></div>
			</p>
			<br clear='both'>
		{% endfor %}
		<hr>

		<footer>
			<p>© Zhopa-popa, 2020</p>
			<p>Все права защищены</p>
		</footer>
	</div>	
	</div>	
	</body>
</html>